version: 2

models:
  - name: mart_full_abbonamenti
    description: "Tabella finale che unisce tutte le informazioni sugli abbonamenti"
    columns:
      - name: order_id
        description: "Chiave primaria dell'ordine"
        tests:
          - unique
          - not_null
      - name: nome_utente
        tests:
          - not_null
      - name: importo_pagato
        